name: Python autotests

on: 
   workflow_dispatch:
      inputs:
         deployment_target:
            description: Choose tests set
            required: true
            type: choice
            default: smoke
            options:
               - smoke
               - regression
               - all

jobs:
  run-tests:
    runs-on: windows-latest
    name: Run autotests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run all tests
        if: github.event.inputs.deployment_target == 'all'
        run: |
          pytest --alluredir=allure-results

      - name: Run smoke tests
        if: github.event.inputs.deployment_target == 'smoke'
        run: |
          pytest -m smoke --alluredir=allure-results

      - name: Run regression tests
        if: github.event.inputs.deployment_target == 'regression'
        run: |
          pytest -m regression --alluredir=allure-results

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
